apiVersion: v1
kind: Pod
metadata:
  name: planner
spec:
  containers:
    - name: planner
      image: <votre-image-planner>
      ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Pod
metadata:
  name: worker
spec:
  containers:
    - name: worker
      image: <votre-image-worker>
      ports:
        - containerPort: 8080
